const products = [
    {
      fileNames: ["IMG-20260317-WA0004.jpg"],
      name: "Seekon Mesh Slip-On Loafer - Grey",
      description: "Lightweight breathable mesh slip-on loafer in cool grey with a vibrant orange and white contrast sole.",
      category: "Sneakers",
      brand: "SEEKON",
      subcategory: "LIFESTYLE",
      price: 8500,
      sizes: ["39", "40", "41", "43", "44"],
      colors: ["grey", "white", "orange"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260301-WA0260.jpg"],
      name: "Air Jordan 1 Low - Royal Blue/Black",
      description: "Classic low-top basketball sneaker featuring a crisp white base with vibrant blue overlays and bold black swoosh details.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "LOW TOPS",
      price: 14500,
      sizes: ["38", "40", "42", "44", "45"],
      colors: ["blue", "white", "black"],
      featuredProduct: true,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260301-WA0261.jpg", "IMG-20260301-WA0262.jpg"],
      name: "Nike Dunk Low - Black/White (Panda)",
      description: "The iconic two-tone streetwear staple featuring a clean white leather base complemented by stark black overlays.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 13000,
      sizes: ["37", "39", "40", "41", "43"],
      colors: ["black", "white"],
      featuredProduct: true,
      newArrival: false,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260301-WA0263.jpg"],
      name: "Air Jordan 1 Low - UNC Powder Blue",
      description: "Premium low-top sneaker featuring a brilliant powder blue and pristine white leather construction inspired by collegiate colors.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "LOW TOPS",
      price: 14000,
      sizes: ["37", "38", "40", "42"],
      colors: ["blue", "white"],
      featuredProduct: false,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260301-WA0264.jpg", "IMG-20260301-WA0265.jpg"],
      name: "Nike SB x Air Jordan 4 - Pine Green",
      description: "Highly coveted skateboarding and basketball hybrid sneaker with a white leather upper, soft grey suede toe, and striking pine green accents.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "BASKETBALL",
      price: 15000,
      sizes: ["40", "41", "43", "44", "45"],
      colors: ["white", "green", "grey"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260301-WA0266.jpg"],
      name: "Nike Dunk High - Spartan Green",
      description: "Classic high-top retro basketball shoe crafted with a smooth white leather base and deep forest green overlays.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "HIGH TOPS",
      price: 13500,
      sizes: ["38", "39", "41", "43", "45"],
      colors: ["green", "white"],
      featuredProduct: false,
      newArrival: false,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260301-WA0267.jpg"],
      name: "Puma Suede Motorsport - Brown/White",
      description: "Sleek motorsport-inspired low-profile sneaker featuring a rich brown suede upper and the signature white side stripe.",
      category: "Sneakers",
      brand: "PUMA",
      subcategory: "LIFESTYLE",
      price: 9500,
      sizes: ["37", "39", "40", "42", "44"],
      colors: ["brown", "white"],
      featuredProduct: false,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260317-WA0003.jpg"],
      name: "Seekon Mesh Slip-On Loafer - Black",
      description: "Modern and breathable black mesh slip-on loafer designed for all-day comfort with a distinctive orange-accented outsole.",
      category: "Sneakers",
      brand: "SEEKON",
      subcategory: "LIFESTYLE",
      price: 8500,
      sizes: ["38", "40", "42", "43", "45"],
      colors: ["black", "white", "orange"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260321-WA0074.jpg", "IMG-20260321-WA0072.jpg", "IMG-20260321-WA0073.jpg"],
      name: "New Balance 9060 - Castlerock Grey",
      description: "Chunky retro-futuristic lifestyle runner featuring a premium mix of grey mesh and suede with a distinctive sculpted midsole.",
      category: "Sneakers",
      brand: "NEW BALANCE",
      subcategory: "LIFESTYLE",
      price: 14200,
      sizes: ["38", "40", "42", "44", "45"],
      colors: ["grey", "silver", "black"],
      featuredProduct: true,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260317-WA0005.jpg"],
      name: "Seekon Mesh Slip-On Loafer - Brown",
      description: "Elegant and breathable brown mesh slip-on loafer designed for effortless summer wear, featuring a striking orange contrast outsole.",
      category: "Sneakers",
      brand: "SEEKON",
      subcategory: "LIFESTYLE",
      price: 8500,
      sizes: ["39", "40", "41", "43", "45"],
      colors: ["brown", "orange", "white"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260320-WA0029.jpg", "IMG-20260320-WA0030.jpg"],
      name: "Premium Designer Trainer - White/Silver",
      description: "Luxury low-top trainer featuring pristine white grained leather, intricate monogram embossing, and metallic silver hardware.",
      category: "Sneakers",
      brand: "SEEKON",
      subcategory: "LOW TOPS",
      price: 15000,
      sizes: ["38", "39", "41", "42", "44"],
      colors: ["white", "silver"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260320-WA0031.jpg"],
      name: "Premium Designer Trainer - Triple Black",
      description: "Sleek luxury streetwear sneaker in a stealthy all-black leather finish, accented with striking silver-tone monogram hardware.",
      category: "Sneakers",
      brand: "SEEKON",
      subcategory: "LOW TOPS",
      price: 15000,
      sizes: ["40", "41", "42", "43", "45"],
      colors: ["black", "silver"],
      featuredProduct: true,
      newArrival: false,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260320-WA0070.jpg"],
      name: "Puma Speedcat Motorsport - Racing Pack",
      description: "Classic low-profile racing sneakers featuring soft suede construction, bold contrast formstrips, and metallic gold foil branding.",
      category: "Sneakers",
      brand: "PUMA",
      subcategory: "LIFESTYLE",
      price: 9200,
      sizes: ["38", "39", "40", "41", "43"],
      colors: ["red", "black", "white", "gold"],
      featuredProduct: false,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260320-WA0079.jpg", "IMG-20260320-WA0081.jpg"],
      name: "Designer Portofino Sneaker - Grey/Black",
      description: "Minimalist premium leather low-top with oversized side logo branding in a versatile and sleek grey/black colorway.",
      category: "Sneakers",
      brand: "SEEKON",
      subcategory: "LOW TOPS",
      price: 13500,
      sizes: ["39", "41", "42", "44"],
      colors: ["grey", "black"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0094.jpg", "IMG-20260327-WA0095.jpg", "IMG-20260327-WA0096.jpg"],
      name: "Nike SB Dunk Low - Powerpuff Girls Buttercup",
      description: "Striking low-top skate shoe featuring a vibrant green upper, solid black swoosh, and unique eye-catching heel details.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 13500,
      sizes: ["38", "39", "41", "42", "44"],
      colors: ["green", "black"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0083.jpg", "IMG-20260327-WA0084.jpg", "IMG-20260327-WA0085.jpg"],
      name: "Nike SB Dunk Low - Concepts Orange Lobster",
      description: "Highly sought-after premium skate shoe featuring varying shades of orange suede, iconic speckled detailing, and a classic plaid inner lining.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 15000,
      sizes: ["39", "40", "42", "43", "45"],
      colors: ["orange", "white", "black"],
      featuredProduct: true,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260327-WA0087.jpg", "IMG-20260327-WA0088.jpg", "IMG-20260327-WA0089.jpg"],
      name: "Nike SB Dunk Low - Jarritos",
      description: "Unique collaboration sneaker featuring a tear-away beige canvas upper overlaying premium white leather, accented with rich green swooshes and orange details.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 14200,
      sizes: ["37", "39", "40", "42", "44"],
      colors: ["beige", "white", "green", "orange"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0091.jpg", "IMG-20260327-WA0092.jpg", "IMG-20260327-WA0093.jpg"],
      name: "Nike SB Dunk Low - Verdy Visty",
      description: "Playful and textured limited-edition sneaker featuring soft pastel corduroy paired with fuzzy green and pink faux-fur overlays.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 14800,
      sizes: ["38", "40", "41", "43", "45"],
      colors: ["blue", "green", "pink", "yellow"],
      featuredProduct: true,
      newArrival: false,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0107.jpg", "IMG-20260327-WA0106.jpg"],
      name: "Nike Dunk Low - Stadium Green/Black",
      description: "Classic low-top sneaker featuring a crisp white leather base highlighted by bold green overlays and a sweeping black heel panel.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 12500,
      sizes: ["38", "40", "42", "44", "45"],
      colors: ["green", "black", "white"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0100.jpg", "IMG-20260327-WA0101.jpg", "IMG-20260327-WA0102.jpg"],
      name: "Nike SB Dunk Low - Ben & Jerry's Chunky Dunky",
      description: "Highly coveted collaboration skate shoe featuring whimsical faux cow hair overlays, a dripping yellow leather swoosh, and a vibrant tie-dye inner lining.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 15000,
      sizes: ["39", "40", "42", "44", "45"],
      colors: ["blue", "green", "yellow", "black", "white"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0103.jpg", "IMG-20260327-WA0104.jpg", "IMG-20260327-WA0105.jpg"],
      name: "Nike SB Dunk Low - Court Purple Suede",
      description: "Premium low-top skate sneaker boasting rich purple suede overlays over a pristine white leather base, finished with a classic gum rubber outsole.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 13800,
      sizes: ["38", "39", "41", "42", "43", "45"],
      colors: ["purple", "white", "brown"],
      featuredProduct: false,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260327-WA0108.jpg", "IMG-20260327-WA0109.jpg"],
      name: "Air Jordan 1 Low - Bred Toe",
      description: "Classic low-top silhouette featuring a striking color-block of crisp white leather, black overlays, and a bold red toe box and heel.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "LOW TOPS",
      price: 14500,
      sizes: ["39", "40", "42", "44", "45"],
      colors: ["black", "white", "red"],
      featuredProduct: true,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260327-WA0110.jpg", "IMG-20260327-WA0111.jpg", "IMG-20260327-WA0114.jpg"],
      name: "Nike Dunk Low - Syracuse Orange",
      description: "Iconic two-tone low-top sneaker featuring a bright white leather base complemented by vibrant orange overlays for a standout streetwear look.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 13200,
      sizes: ["37", "38", "40", "41", "43"],
      colors: ["orange", "white"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0116.jpg", "IMG-20260327-WA0117.jpg"],
      name: "Nike Dunk Low - Cacao Wow",
      description: "Versatile and earthy low-top sneaker featuring rich brown leather overlays atop a clean, slightly off-white vintage base.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 13800,
      sizes: ["38", "39", "41", "42", "44", "45"],
      colors: ["brown", "white", "cream"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0118.jpg", "IMG-20260327-WA0119.jpg", "IMG-20260327-WA0120.jpg"],
      name: "Nike Dunk Low - Medium Olive",
      description: "Clean and understated classic dunk featuring a crisp white leather upper perfectly contrasted by smooth medium olive green panels and swoosh.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 13500,
      sizes: ["38", "40", "42", "43", "45"],
      colors: ["olive", "white"],
      featuredProduct: false,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260327-WA0130.jpg", "IMG-20260327-WA0131.jpg", "IMG-20260327-WA0132.jpg"],
      name: "Nike SB Dunk Low - White/Black Gum",
      description: "Clean and versatile low-top skate shoe featuring a crisp white leather upper, a contrasting black swoosh, and a classic gum rubber outsole.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 13500,
      sizes: ["38", "40", "41", "43", "45"],
      colors: ["white", "black", "tan"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: [
        "IMG-20260327-WA0121.jpg", 
        "IMG-20260327-WA0122.jpg", 
        "IMG-20260327-WA0123.jpg", 
        "IMG-20260327-WA0124.jpg",
        "IMG-20260327-WA0146.jpg",
        "IMG-20260327-WA0147.jpg"
      ],
      name: "Nike Dunk Low - Team Red",
      description: "Iconic two-tone sneaker featuring a smooth white leather base overlaid with deep, rich burgundy and team red panels.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 13200,
      sizes: ["39", "40", "42", "44", "45"],
      colors: ["burgundy", "white"],
      featuredProduct: false,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260327-WA0125.jpg"],
      name: "Puma Speedcat Motorsport - Brown Suede",
      description: "Sleek low-profile racing sneaker featuring a premium brown suede upper, contrasting white formstrip, and gold foil branding.",
      category: "Sneakers",
      brand: "PUMA",
      subcategory: "LIFESTYLE",
      price: 8500,
      sizes: ["37", "39", "40", "42", "44"],
      colors: ["brown", "white", "gold"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0126.jpg", "IMG-20260327-WA0127.jpg"],
      name: "Puma Speedcat Motorsport - Racing Red",
      description: "Bold motorsport-inspired lifestyle shoe in vibrant red suede, detailed with a crisp white formstrip and classic Puma branding.",
      category: "Sneakers",
      brand: "PUMA",
      subcategory: "LIFESTYLE",
      price: 8800,
      sizes: ["38", "40", "41", "43", "45"],
      colors: ["red", "white", "gold"],
      featuredProduct: true,
      newArrival: false,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0128.jpg"],
      name: "Puma Speedcat Motorsport - Black/Pink",
      description: "Modern take on the classic racing silhouette featuring a stealthy black suede upper contrasted by a soft pink side stripe.",
      category: "Sneakers",
      brand: "PUMA",
      subcategory: "LIFESTYLE",
      price: 8500,
      sizes: ["37", "38", "40", "41", "42"],
      colors: ["black", "pink"],
      featuredProduct: false,
      newArrival: true,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260327-WA0129.jpg"],
      name: "Puma Speedcat Motorsport - Black/White",
      description: "Essential low-profile driving sneaker crafted in black suede with a striking white formstrip and metallic gold logos.",
      category: "Sneakers",
      brand: "PUMA",
      subcategory: "LIFESTYLE",
      price: 9000,
      sizes: ["39", "41", "42", "44", "45"],
      colors: ["black", "white", "gold"],
      featuredProduct: true,
      newArrival: false,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0133.jpg", "IMG-20260327-WA0134.jpg", "IMG-20260327-WA0135.jpg"],
      name: "Nike SB Dunk Low - Civilist",
      description: "Innovative heat-reactive collaboration sneaker that transitions from a sleek matte black finish to a vibrant, multi-colored thermal map pattern.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 14800,
      sizes: ["38", "40", "41", "43", "44", "45"],
      colors: ["black", "green", "blue", "red", "yellow"],
      featuredProduct: true,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260327-WA0136.jpg", "IMG-20260327-WA0137.jpg", "IMG-20260327-WA0138.jpg"],
      name: "Nike SB Dunk Low - Born x Raised",
      description: "Commemorative low-top featuring premium white leather, rich blue nubuck overlays, holographic swooshes, and custom cross-perforated toe box details.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 15000,
      sizes: ["37", "39", "40", "42", "44"],
      colors: ["blue", "white", "silver"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0140.jpg"],
      name: "Nike Dunk Low - Midnight Navy",
      description: "Classic two-tone dunk silhouette featuring a clean white leather base sharply contrasted by deep midnight navy overlays.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 13500,
      sizes: ["38", "40", "42", "43", "45"],
      colors: ["navy", "white"],
      featuredProduct: false,
      newArrival: false,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0141.jpg", "IMG-20260327-WA0142.jpg"],
      name: "Nike SB Dunk Low - Travis Scott",
      description: "Highly sought-after collaboration skate shoe featuring a unique tear-away navy bandana pattern, plaid quarter panels, and earthy tan accents.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 15000,
      sizes: ["39", "40", "42", "43", "45"],
      colors: ["navy", "white", "tan", "brown"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0143.jpg", "IMG-20260327-WA0144.jpg", "IMG-20260327-WA0145.jpg"],
      name: "Nike SB Dunk Low - Crenshaw Skate Club",
      description: "Premium skate shoe featuring a unique green and burgundy scratch-off overlay, beige base, and a striking pastel blue swoosh.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 14500,
      sizes: ["38", "39", "41", "44", "45"],
      colors: ["green", "burgundy", "beige", "blue"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0148.jpg", "IMG-20260327-WA0149.jpg", "IMG-20260327-WA0150.jpg"],
      name: "Air Jordan 1 Low OG - Travis Scott Mocha",
      description: "Legendary low-top collaboration featuring a premium dark brown suede base, black accents, and the signature oversized backwards sail swoosh.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "LOW TOPS",
      price: 15000,
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["brown", "black", "cream"],
      featuredProduct: true,
      newArrival: false,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0151.jpg", "IMG-20260327-WA0152.jpg"],
      name: "Air Jordan 1 Low OG - Travis Scott Olive",
      description: "Exclusive collaboration showcasing a stealthy black suede base, crisp white leather overlays, and a bold olive green backwards swoosh.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "LOW TOPS",
      price: 14800,
      sizes: ["38", "39", "40", "42", "44"],
      colors: ["black", "white", "olive"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0153.jpg", "IMG-20260327-WA0154.jpg"],
      name: "Air Jordan 1 Low OG - Travis Scott Reverse Mocha",
      description: "Highly coveted low-top featuring a rich brown suede base, premium white leather overlays, and the signature oversized cream backwards swoosh.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "LOW TOPS",
      price: 15000,
      sizes: ["39", "41", "42", "43", "45"],
      colors: ["brown", "white", "cream"],
      featuredProduct: true,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260327-WA0155.jpg", "IMG-20260327-WA0156.jpg", "IMG-20260327-WA0157.jpg"],
      name: "Air Jordan 1 Low OG - Travis Scott Pink/Sail",
      description: "Unique and vibrant take on the classic collaboration, featuring soft pastel pink panels contrasted by a prominent cream-colored backwards swoosh.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "LOW TOPS",
      price: 14500,
      sizes: ["37", "38", "39", "41", "42"],
      colors: ["pink", "white", "cream"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0158.jpg", "IMG-20260327-WA0159.jpg"],
      name: "Air Jordan 1 High OG - Travis Scott Mocha",
      description: "The sneaker that started the hype, featuring a premium white leather and dark mocha suede upper, complete with a hidden stash pocket and iconic black reverse swoosh.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "HIGH TOPS",
      price: 15000,
      sizes: ["40", "41", "42", "44", "45"],
      colors: ["brown", "white", "black"],
      featuredProduct: true,
      newArrival: false,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0160.jpg", "IMG-20260327-WA0161.jpg"],
      name: "Air Jordan 1 High OG - Travis Scott x Fragment",
      description: "Legendary three-way collaboration blending crisp white leather with vibrant military blue accents and the signature oversized black swoosh.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "HIGH TOPS",
      price: 15000,
      sizes: ["39", "40", "42", "43", "45"],
      colors: ["blue", "white", "black"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0162.jpg", "IMG-20260327-WA0163.jpg", "IMG-20260327-WA0164.jpg"],
      name: "Air Jordan 1 High - Dior",
      description: "Ultra-premium luxury collaboration featuring smooth grey and white leather, detailed with the iconic Dior Oblique monogram swoosh and icy translucent outsoles.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "HIGH TOPS",
      price: 15000,
      sizes: ["39", "40", "42", "44", "45"],
      colors: ["grey", "white", "black"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0165.jpg", "IMG-20260327-WA0166.jpg", "IMG-20260327-WA0167.jpg"],
      name: "Air Jordan 1 High - Fearless",
      description: "Striking high-top crafted entirely from glossy patent leather, boldly splitting the iconic UNC powder blue and Chicago red colorways into one standout design.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "HIGH TOPS",
      price: 14500,
      sizes: ["38", "40", "41", "43", "44"],
      colors: ["red", "blue", "white", "black"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0168.jpg", "IMG-20260327-WA0169.jpg"],
      name: "Air Jordan 1 High - Varsity Red",
      description: "A timeless classic featuring the quintessential red, white, and black color-blocking on a premium high-top leather silhouette.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "HIGH TOPS",
      price: 14000,
      sizes: ["39", "41", "42", "43", "45"],
      colors: ["red", "white", "black"],
      featuredProduct: true,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260327-WA0170.jpg", "IMG-20260327-WA0171.jpg"],
      name: "Air Jordan 1 High - Off-White UNC",
      description: "Highly coveted deconstructed sneaker featuring a powder blue and white colorway, exposed stitching, oversized branding, and signature zip-tie detailing.",
      category: "Sneakers",
      brand: "JORDAN",
      subcategory: "HIGH TOPS",
      price: 15000,
      sizes: ["38", "40", "42", "44", "45"],
      colors: ["blue", "white", "orange", "black"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260328-WA0052.jpg"],
      name: "Adidas Response CL - Silver Metallic",
      description: "Retro-inspired running silhouette featuring a breathable white mesh base layered with bold metallic silver overlays and classic black stripe detailing.",
      category: "Sneakers",
      brand: "ADIDAS",
      subcategory: "RUNNING",
      price: 12500,
      sizes: ["38", "40", "41", "43", "45"],
      colors: ["silver", "white", "black"],
      featuredProduct: false,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0172.jpg", "IMG-20260327-WA0173.jpg"],
      name: "Nike SB Dunk Low - Raygun Tie-Dye Black",
      description: "Vibrant skate shoe paying homage to the fictional Roswell Rayguns, featuring black leather alongside orange and yellow tie-dye patterns and the signature alien embroidery.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 14500,
      sizes: ["39", "40", "42", "44", "45"],
      colors: ["black", "orange", "yellow", "white"],
      featuredProduct: true,
      newArrival: false,
      flashSale: true
    },
    {
      fileNames: ["IMG-20260327-WA0174.jpg"],
      name: "Nike SB Dunk Low - Supreme Rammellzee",
      description: "Highly coveted collaboration featuring durable black suede overlays contrasting with vibrant canvas panels showcasing the legendary artwork of Rammellzee, finished with a gold dubrae.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 15000,
      sizes: ["38", "39", "41", "43", "44"],
      colors: ["black", "white", "gold", "pink", "blue"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0175.jpg", "IMG-20260327-WA0176.jpg", "IMG-20260327-WA0177.jpg"],
      name: "Nike LDWaffle x Sacai - Varsity Blue",
      description: "Avant-garde collaboration blending two vintage running models into one, featuring doubled-up swooshes, tongues, and laces in a vibrant primary color palette.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LIFESTYLE",
      price: 14800,
      sizes: ["37", "39", "40", "42", "45"],
      colors: ["blue", "red", "yellow", "silver"],
      featuredProduct: true,
      newArrival: false,
      flashSale: false
    },
    {
      fileNames: ["IMG-20260327-WA0178.jpg", "IMG-20260327-WA0179.jpg"],
      name: "Nike SB Dunk Low - eBay Sandy Bodecker",
      description: "A historic tribute featuring the iconic eBay color scheme constructed with glossy patent leather and distinctive clear TPU 'cut' panels bridging the design.",
      category: "Sneakers",
      brand: "NIKE",
      subcategory: "LOW TOPS",
      price: 15000,
      sizes: ["40", "41", "42", "44", "45"],
      colors: ["red", "yellow", "blue", "green", "white"],
      featuredProduct: true,
      newArrival: true,
      flashSale: false
    }
  ];
  
export default products;